spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: hs8569710!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
